### PR TITLE
Added option for storing of cached password

### PR DESCRIPTION
**Pull request by aligndbot**
Sometimes its just nessessary to store password between the launches. Thats what `cachedPasswordPath` option is for.

### CODE REVIEW

**Comment by darvin** [comment]
+1

**Comment by calmh** [comment]
No. We will not save the user's password to disk, unencrypted.

**Comment by darvin** [comment]
would it be merged if cachedpassword would be passed as option?

**Comment by calmh** [comment]
That seems like it could be fine.

**Pull request closed without merging**
